export const types = [
	'All',
	'Pencil Sketching',
	'Charcoal Painting',
	'Painting',
	'Drawing',
];

export const allLanguages = ['English', 'Hindi'];

export const searchKeywords = [
	'Pencil sketching',
	'Charcoal painting',
	'Painting',
	'Drawing',
	'Learn To Draw #01',
	'Learn To Draw #02',
	'Learn To Draw #03',
	'Learn To Draw #04',
	'Learn To Draw #05',
	'Learn To Draw #06',
	'Learn To Draw #07',
	'Learn To Draw #08',
	'Learn To Draw #09',
	'Learn To Draw #10',
	'Learn To Draw #11',
	'Learn To Draw #12',
	'Learn To Draw #13',
	'Learn To Draw #14',
	'Learn To Draw #15',
	'Learn To Draw #16',
	'Drawing for Beginners - Step by Step | Day - 002',
	'Drawing for Beginners - Step by Step | Day - 003',
	'Drawing for Beginners - Step by Step | Day - 004',
	'Drawing for Beginners - Step by Step | Day - 005',
	'Drawing for Beginners - Step by Step | Day - 006',
	'Drawing for Beginners - Step by Step | Day - 007',
	'Drawing for Beginners - Step by Step | Day - 013',
	'Drawing for Beginners - Step by Step | Day - 014',
	'Drawing for Beginners - Step by Step | Day - 015',
	'Drawing for Beginners - Step by Step | Day - 016',
	'Drawing for Beginners - Step by Step | Day - 017',
];
